language: rust
sudo: false

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

cache: cargo

env:
  matrix:
    - FEATURE=accelerate
    - FEATURE=netlib
    - FEATURE=openblas

  global:
    - secure: CAsWkX68mwPcXVNOiBaekoq8lMWgKRhVVyNhmT2ruMpAbeTmnDLzs9IFWOjvytacMv/YH8Z85HedWxIcg7m6gCIdpIOeNqlDUvGi3T18UdIu55pp6ScOcCyHd762OsC1UGOCudVIBDwK1a8gm6D/6xzzrbxPT3Bs99HXF/vL+E8=

matrix:
  exclude:
    - os: linux
      env: FEATURE=accelerate

before_install:
  - curl https://stainless-steel.github.io/travis/gfortran.sh | bash

script:
  - cargo test --no-default-features --features=$FEATURE --verbose
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench --no-default-features --features=$FEATURE --verbose;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$FEATURE" == "openblas" ]; then
      curl https://stainless-steel.github.io/travis/documentation.sh | bash;
    fi

notifications:
  email: false

addons:
  apt:
    sources:
      - kubuntu-backports

    packages:
      - cmake
      - gfortran
