language: rust

before_install:
  - sudo add-apt-repository --yes ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - sudo apt-get install gfortran

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: Y7TJkTSYoX9/51FCU1zI5WRbazVE0TYv2QXTJaZ2MMMki+tvgXWEDExsbZWxrPx2qe3NVKcqJs5fe7Hsdze+X1ydJmubADrk+Fxivxp+19/c7fH4rw8O+XEyT33DzhqVbK6qi50KNrDBkbYYgI2J7NQLPeRgSWIOCmRjWKISJ3c=
