[package]
name = "blas"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[dependencies.libblas-sys]
git = "https://github.com/stainless-steel/libblas-sys"

[dev-dependencies.assert]
git = "https://github.com/stainless-steel/assert"
