[package]
name = "blas"
version = "0.0.19"
authors = ["Corey Richardson <corey@octayn.net>", "Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/blas"
homepage = "https://github.com/stainless-steel/blas"
documentation = "https://stainless-steel.github.io/blas"
description = "The package provides an interface to the Basic Linear Algebra Subprograms."

[dependencies]
num = "*"

[dependencies.libblas-sys]
version = "*"

[dev-dependencies]
quickcheck = "*"
