[package]
name = "blas"
version = "0.8.0"
authors = [
  "Andrew Straw <strawman@astraw.com>",
  "Corey Richardson <corey@octayn.net>",
  "Ivan Ukhov <ivan.ukhov@gmail.com>",
]
license = "MIT"
repository = "https://github.com/stainless-steel/blas"
homepage = "https://github.com/stainless-steel/blas"
documentation = "https://stainless-steel.github.io/blas"
description = "The package provides an interface to the Basic Linear Algebra Subprograms."

[features]
default = ["openblas"]

accelerate = ["blas-sys/accelerate"]
netlib = ["blas-sys/netlib"]
openblas = ["blas-sys/openblas"]

[dependencies]
complex = "0.7"
libc = "*"

[dependencies.blas-sys]
version = "0.2"
default-features = false
